version: '3.8'

services:
  postgres:
    container_name: nest_psql_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASS
      - POSTGRES_DB=$DATABASE_NAME
    volumes:
      - nest_psql:/data/postgres
    ports:
      - "$DATABASE_PORT:5432"
    restart: unless-stopped

volumes:
  nest_psql:
